Reorganiza búsqueda y comprobación de Dockerfile
Aisla la búsqueda y comprobación del fichero encontrado en
before_script, manteniendo la lógica de script sin complejidad
adicional.

diff --git a/_packaging.yml b/_packaging.yml
--- a/_packaging.yml
+++ b/_packaging.yml
@@ -25,20 +25,18 @@ lint-dockerfile:
     - >
       if [ -z "${DOCKERFILE_PATH}" ];
       then
-        export DOCKERFILE_PATH=$(find -name "${DOCKERFILE_NAME}");
+        dockerfilePath=$(find -name "${DOCKERFILE_NAME}");
+        if [ -f "${dockerfilePath}" ];
+        then
+          echo "Detected '${dockerfilePath}' Dockerfile, nice!";
+          export DOCKERFILE_PATH="${dockerfilePath}";
+        else
+          echo "DOCKERFILE_PATH is undefined and Dockerfile with name '${DOCKERFILE_NAME}' not found in project!";
+          exit 1;
+        fi;
       fi;
   script:
-    - >
-      if [ -z "${DOCKERFILE_PATH}" ];
-      then
-        echo "Dockerfile with name '${DOCKERFILE_NAME}' not found in project!";
-        exit 1;
-      elif [ ! -f "${DOCKERFILE_PATH}" ];
-      then
-        echo "Dockerfile '${DOCKERFILE_PATH}' is not a valid file!";
-        exit 1;
-      fi;
-      docker run --rm -i ${LINT_IMAGE_NAME}:${LINT_IMAGE_TAG} < "${DOCKERFILE_PATH}";
+    - docker run --rm -i ${LINT_IMAGE_NAME}:${LINT_IMAGE_TAG} < "${DOCKERFILE_PATH}";
   allow_failure: true
   rules:
     - if: $CI_MERGE_REQUEST_ID ||
